
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\alertgene.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\betterdiscord.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\bio-tolerance.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\biotune.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\dailyinternetlife.com.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\midlet.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\sextine.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\shell.sublime-project"
start "" "E:\data\portable\standards\sublime_text_build_4126_x64\sublime_text.exe" "X:\development\sublime\youtube-watched-videos-hider.sublime-project"
